name: Push/PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: none

jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        platform: [ ubuntu-latest, ubuntu-24.04-arm ]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -o app .

      - uses: kubernetes-sigs/kwok@4b79482a138149032d5817ff262a95f7da4a9394
        with:
          command: kwokctl
      - run: kwokctl create cluster
        env:
          # Please keep this in sync with the devenv/kwok/docker-compose file
          KWOK_KUBE_VERSION: v1.33.0
      - name: Test
        env:
          PLATFORM: ${{ matrix.platform}}
        run: |
          # Minikube only works on amd
          export TEST_KUBECONFIG="${HOME}/.kube/config"
          go test -count=1 ./...

  build-container:
    name: Build container image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: Build contianer
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: false
          tags: ci.local/kube-node-labeler:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.1
          only-new-issues: "true"
